### PR TITLE
Add missing {octicons/prDrafted} placeholder

### PR DESCRIPTION
**Pull request by Andre601**
## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

There was a placeholder missing for the PR drafted icon. I now added it as `{octicons/prDrafted}`

Closes #

[contributing]: https://github.com/Readme-Workflows/.github/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Review by PuneetGopinath — APPROVED** [review]
Cool

**Review by abhijoshi2k — APPROVED** [review]

**Comment by abhijoshi2k** [comment]
@Andre601 Is this PR ready?

**Comment by PuneetGopinath** [comment]
> @Andre601 Is this PR ready?

Don't know if it's ready, there is no status label. Don't merge.

**Comment by Andre601** [comment]
It is ready

**Pull request merged**
